# Generated by Django 3.1.7 on 2021-04-02 11:39

from django.db import migrations
from django.conf import settings

def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk-2, username="admin", is_active=True, email="admin@admin.com")
    user.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
