# Generated by Django 3.1.7 on 2021-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
